name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: us-central1-docker.pkg.dev/as-rudgus4620/gcf-artifacts/geminai-chatbot:latest
      NEXT_PUBLIC_GEMINAI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINAI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        run: |
          echo "Installing Google Cloud SDK..."
          curl -sSL https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud init

      - name: Log in to GCP
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file $HOME/gcp-key.json
          gcloud auth login

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          # Build the Docker image
          docker build --build-arg NEXT_PUBLIC_GEMINAI_API_KEY=${NEXT_PUBLIC_GEMINAI_API_KEY} -t $IMAGE_URI .
          # Push the Docker image
          docker push $IMAGE_URI
