name: Build and Push Docker Image

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: us-central1-docker.pkg.dev/my-gcp-project/my-repo/my-image:latest
      NEXT_PUBLIC_GEMINAI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINAI_API_KEY }}  # 환경 변수로 설정
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker build --build-arg NEXT_PUBLIC_GEMINAI_API_KEY=${NEXT_PUBLIC_GEMINAI_API_KEY} -t $IMAGE_URI .
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file $HOME/gcp-key.json
          gcloud auth configure-docker ${IMAGE_URI}
          docker push $IMAGE_URI