name: GCP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCP credentials
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | tr -d '\r' > /home/runner/gcp-key.json

      - name: Authenticate to GCP
        run: gcloud auth activate-service-account --key-file=/home/runner/gcp-key.json

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/as-rudgus/geminai-chat:latest .
          docker push us-central1-docker.pkg.dev/as-rudgus/geminai-chat:latest
