name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: us-central1-docker.pkg.dev/as-rudgus4620/gcf-artifacts/geminai-chatbot:latest
      NEXT_PUBLIC_GEMINAI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINAI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud authentication
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: as-rudgus4620
          export_default_credentials: true

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          # Build the Docker image
          docker build --build-arg NEXT_PUBLIC_GEMINAI_API_KEY=${NEXT_PUBLIC_GEMINAI_API_KEY} -t $IMAGE_URI .
          # Push the Docker image
          docker push $IMAGE_URI
